language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing to be installed"


#Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  -docker --version
  -docker build -t simple-node .
  -docker tag simple-node moshud/simple-node:node.v1

  #Tasks to perform after the process is successful. 
  after_success:
    -echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_USERNAME"  --password-stdin
    - docker push moshud/simple-node

".travis.yml" 24L, 495C